//
//  render_layer_labels.hpp
//  Make The Thing
//
//  Created by Toby Rosenberg on 12/29/20.
//  Copyright © 2020 Toby Rosenberg. All rights reserved.
//

#ifndef render_layer_labels_hpp
#define render_layer_labels_hpp

#define LAYER_LABEL_ENTRIES \
LAYER_LABEL_ENTRY(LAYER_LABEL_STATIC, 4000), \
LAYER_LABEL_ENTRY(LAYER_LABEL_STATIC_INSTANCING, 1000), \
LAYER_LABEL_ENTRY(LAYER_LABEL_STATIC_INSTANCING_CANVAS, 256), \
LAYER_LABEL_ENTRY(LAYER_LABEL_STATIC_CANVAS, 1), \
LAYER_LABEL_ENTRY(LAYER_LABEL_STATIC_CANVAS_HSV, 1), \
LAYER_LABEL_ENTRY(LAYER_LABEL_DYNAMIC, 4000), \
LAYER_LABEL_ENTRY(LAYER_LABEL_DYNAMIC_CANVAS, 1000), \
LAYER_LABEL_ENTRY(LAYER_LABEL_DYNAMIC_BG_LAYER_PER_FRAME, 4000), \
LAYER_LABEL_ENTRY(LAYER_LABEL_DYNAMIC_BG_LAYER, 1000), \
LAYER_LABEL_ENTRY(LAYER_LABEL_DRAWING, 1000), \
LAYER_LABEL_ENTRY(LAYER_LABEL_PER_FRAME, 1000), \
LAYER_LABEL_ENTRY(LAYER_LABEL_PER_FRAME_WORLD, 100), \
LAYER_LABEL_ENTRY(LAYER_LABEL_DRAWING_BUFFER, 1000), \
LAYER_LABEL_ENTRY(LAYER_LABEL_UI, 1000), \
\
LAYER_LABEL_ENTRY(LAYER_LABEL_DEBUG_STATIC, 1000), \
LAYER_LABEL_ENTRY(LAYER_LABEL_DEBUG_DYNAMIC, 1000), \
LAYER_LABEL_ENTRY(LAYER_LABEL_DEBUG_DYNAMIC_CONNECTIONS, 1000), \
\
LAYER_LABEL_ENTRY(LAYER_LABEL_IMAGES, 1000), \
LAYER_LABEL_ENTRY(LAYER_LABEL_COLLISION_DEBUG, 1000), \
LAYER_LABEL_ENTRY(LAYER_LABEL_INSTANCES, 1000), \
LAYER_LABEL_ENTRY(LAYER_LABEL_DRAWTALK_DYNAMIC_PER_FRAME, 8000), \
LAYER_LABEL_ENTRY(LAYER_LABEL_DRAWTALK_DYNAMIC_PER_FRAME_UI, 8000), \
LAYER_LABEL_ENTRY(LAYER_LABEL_CANVAS_PER_FRAME, 100), \
LAYER_LABEL_ENTRY(LAYER_LABEL_SHADOW_IMAGES, 100), \
LAYER_LABEL_ENTRY(LAYER_LABEL_BACKGROUND_CANVAS, 100), \
LAYER_LABEL_ENTRY(LAYER_LABEL_PER_FRAME_TEMP, 1000), \
LAYER_LABEL_ENTRY(LAYER_LABEL_DYNAMIC____DEBUG, 100000), \
LAYER_LABEL_ENTRY(LAYER_LABEL_DYNAMIC_LIGHTS, 1000), \
LAYER_LABEL_ENTRY(LAYER_LABEL_DYNAMIC_TEST, 1000), \
LAYER_LABEL_ENTRY(LAYER_LABEL_PER_FRAME_WORLD_2, 10000), \
LAYER_LABEL_ENTRY(LAYER_LABEL_PER_FRAME_SCREEN_2, 10000),\
LAYER_LABEL_ENTRY(LAYER_LABEL_LINE_TEST, 10000)\

typedef enum LAYER_LABEL {
#define LAYER_LABEL_ENTRY(a, b) a
    LAYER_LABEL_ENTRIES,
#undef LAYER_LABEL_ENTRY
    LAYER_LABEL_COUNT
} LAYER_LABEL;

static usize layer_label_sizes[LAYER_LABEL_COUNT] = {
#define LAYER_LABEL_ENTRY(a, b) b
LAYER_LABEL_ENTRIES
#undef LAYER_LABEL_ENTRY
};

#undef LAYER_LABEL_ENTRIES

#endif /* render_layer_labels_hpp */
